// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReviewApplicationAPI.Data;

#nullable disable

namespace MovieReviewApplicationAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieReviewApplicationAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieName = "Wild Robot"
                        },
                        new
                        {
                            Id = 2,
                            MovieName = "Inside Out 2"
                        },
                        new
                        {
                            Id = 3,
                            MovieName = "Iron Giant"
                        });
                });

            modelBuilder.Entity("MovieReviewApplicationAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            ReviewComment = "Excellent animation"
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            ReviewComment = "Excellent concept"
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 3,
                            ReviewComment = "Excellent story"
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            ReviewComment = "Heart warming"
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 2,
                            ReviewComment = "Emotional"
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 3,
                            ReviewComment = "Made me cry"
                        });
                });

            modelBuilder.Entity("MovieReviewApplicationAPI.Models.Review", b =>
                {
                    b.HasOne("MovieReviewApplicationAPI.Models.Movie", "movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");
                });
#pragma warning restore 612, 618
        }
    }
}
